title: Ebook-template
description: Template to create PDF, ePub and Kindle books with Asciidoc and dblatex
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
